Sense Vault Actions
fiatdao/actions pull request #16
Opened 2022-09-24 14:57 UTC by lacoop6tu

WIP
- add initial actions integration and tests

2022-09-28 15:29 UTC, SolcAndMe requested changes

2022-09-28 15:29 UTC, SolcAndMe commented on src/test/utils/VaultSPT.sol
> +
remove empty line

2022-09-28 15:29 UTC, SolcAndMe commented on src/test/utils/VaultSPT.sol
> +
remove empty line

2022-09-28 15:29 UTC, SolcAndMe commented on src/test/utils/VaultSPT.sol
> +contract VaultSPT is Guarded, IVault {
remove contract and import it from vaults

2022-09-28 15:29 UTC, SolcAndMe commented on src/vault/VaultSPTActions.sol
> +
align code style, remove empty lines throughout the contract ...

2022-09-28 15:29 UTC, SolcAndMe commented on src/vault/VaultSPTActions.sol
> +        uint256 tBal = divider.redeem(swapParams.adapter,swapParams.maturity,pTokenAmount);
naming not aligned with rest of contracts

2022-11-02 17:05 UTC, SolcAndMe approved these changes

2022-11-02 17:39 UTC, amarcu reviewed
Looks good, added only a few minor typos.

2022-11-02 18:00 UTC, SolcAndMe commented on src/lever/LeverSPTActions.sol
> +    /// @param upfrontUnderliers Amount of underliers the `collateralizer` puts up up front [underlierScale]
no this correct. upfront should be together though.

2022-11-02 18:01 UTC, SolcAndMe commented
same typos are prob. also in LeverEPTActions

2022-11-02 18:01 UTC, SolcAndMe commented
@lacoop6tu

2022-11-02 19:25 UTC, lacoop6tu commented on src/lever/LeverSPTActions.sol
> +    /// @param fiatSwapParams Parameters of the underlier to FIAT swap
added ty!

2022-11-02 19:27 UTC, merged